### ISSUE TITLE
dependency not calculated with Fortran 2008 module use

### ISSUE THREAD

**Issue by wadudmiah** [outpaddling/makedepf90#2]
Hello,

The makedepf90 does not understand Fortran 2008 module use using double-colon, e.g.

`use :: module_mod`

Could this be fixed please?

Cheers,

**Comment by outpaddling** [comment]
Sorry, I'm not going to have time to work on this any time soon.  FYI, I did not develop makedepf90, but  created this repo after realizing the project had been abandoned, so that there would be a reliable download site and opportunity to maintain it.  If someone submits a working patch for this issue, I will gladly incorporate it.

**Comment by outpaddling** [comment]
Feedback timeout.
